create table base_user(
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  USER_NO VARCHAR(20) NOT NULL,
  USER_NAME VARCHAR(64) NOT NULL DEFAULT '',
  PASSWORD VARCHAR(128) NOT NULL DEFAULT '',
  EMAIL VARCHAR(64) NOT NULL DEFAULT '',
  TELEPHONE VARCHAR(16) NOT NULL DEFAULT '',
  STATE INT(10) NOT NULL DEFAULT 0,
  CREATED_AT DATETIME NOT NULL DEFAULT now(),
  UPDATED_AT DATETIME NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX index_u_n_t_e ON base_user(USER_NO, USER_NAME, TELEPHONE, EMAIL);